import type { StyleMap } from './types';

export const S: StyleMap = {
  app: {
    fontFamily: "-apple-system,BlinkMacSystemFont,'SF Pro Display',sans-serif",
    maxWidth: 430,
    margin: '0 auto',
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    background: '#F0F2F5',
  },
  splash: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100dvh' },
  loader: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    border: '3px solid #E4F5EF',
    borderTopColor: '#0F7A5A',
    animation: 'spin .7s linear infinite',
  },
  screen: { flex: 1, overflowY: 'auto' },
  toast: {
    position: 'fixed',
    top: 16,
    left: '50%',
    transform: 'translateX(-50%)',
    background: '#0D1B2A',
    color: '#fff',
    padding: '10px 20px',
    borderRadius: 24,
    fontSize: 14,
    fontWeight: 600,
    zIndex: 200,
    whiteSpace: 'nowrap',
  },
  hero: { background: '#0D1B2A', padding: '52px 24px 28px' },
  eyebrow: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#3D6B7A',
    marginBottom: 8,
  },
  heroAmt: { fontSize: 44, fontWeight: 800, color: '#fff', letterSpacing: -1.5, lineHeight: 1, marginBottom: 6 },
  heroSub: { fontSize: 18, color: '#3D8FA8', fontWeight: 500, marginBottom: 12 },
  heroDate: { fontSize: 12, color: '#2D5060', fontStyle: 'italic' },
  section: { padding: '12px 16px 0' },
  slbl: {
    fontSize: 11,
    fontWeight: 700,
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  cCard: { background: '#fff', borderRadius: 16, padding: '14px 14px 16px' },
  cLbl: {
    fontSize: 11,
    fontWeight: 600,
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  cAmt: { fontSize: 19, fontWeight: 800 },
  soldeCard: { background: '#fff', borderRadius: 16, padding: '18px 18px 16px' },
  cardW: { background: '#fff', borderRadius: 16, padding: '16px' },
  ctitle: {
    fontSize: 11,
    fontWeight: 700,
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  row: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '9px 0' },
  nav: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: 430,
    display: 'flex',
    background: '#fff',
    borderTop: '1px solid #EBEBEB',
    paddingBottom: 'env(safe-area-inset-bottom,6px)',
    zIndex: 100,
  },
  navBtn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '9px 0 6px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    gap: 3,
  },
  fp: { paddingBottom: 100 },
  fhdr: { background: '#0D1B2A', color: '#fff', padding: '52px 20px 20px', fontSize: 22, fontWeight: 800, letterSpacing: -0.5 },
  fc: { margin: '16px', background: '#fff', borderRadius: 16, padding: '18px' },
  inp: {
    display: 'block',
    width: '100%',
    boxSizing: 'border-box',
    padding: '12px 14px',
    borderRadius: 10,
    border: '1.5px solid #E8E8E8',
    fontSize: 15,
    color: '#111',
    background: '#FAFAFA',
    outline: 'none',
    appearance: 'none',
    marginBottom: 2,
    fontFamily: 'inherit',
  },
  btnP: {
    width: '100%',
    padding: '14px',
    borderRadius: 12,
    border: 'none',
    background: '#0D1B2A',
    color: '#fff',
    fontSize: 16,
    fontWeight: 700,
    cursor: 'pointer',
    marginTop: 18,
    fontFamily: 'inherit',
  },
  btnGhost: {
    width: '100%',
    padding: '12px',
    borderRadius: 10,
    border: '1.5px solid #ddd',
    background: 'none',
    color: '#555',
    fontSize: 14,
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginTop: 4,
  },
  seg: { display: 'flex', margin: '14px 16px 0', background: '#E8E8E8', borderRadius: 10, padding: 3, gap: 2 },
  segB: {
    flex: 1,
    padding: '9px 4px',
    borderRadius: 8,
    border: 'none',
    background: 'none',
    fontSize: 13,
    color: '#777',
    cursor: 'pointer',
    fontWeight: 500,
    fontFamily: 'inherit',
  },
  segA: { background: '#fff', color: '#0D1B2A', fontWeight: 700, boxShadow: '0 1px 3px rgba(0,0,0,.1)' },
  err: { background: '#FDEAEA', color: '#A32D2D', borderRadius: 10, padding: '9px 12px', fontSize: 13, marginTop: 8 },
  info: { background: '#EEF6F3', color: '#0D5A3F', borderRadius: 10, padding: '10px 12px', fontSize: 13, marginBottom: 14, lineHeight: 1.5 },
  delBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    border: 'none',
    background: '#FDEAEA',
    color: '#A32D2D',
    cursor: 'pointer',
    fontSize: 14,
    flexShrink: 0,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,.45)',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    zIndex: 150,
  },
  modal: { background: '#fff', borderRadius: '20px 20px 0 0', padding: '28px 24px 40px', width: '100%', maxWidth: 430 },
};

export const CSS = `
*{-webkit-tap-highlight-color:transparent;box-sizing:border-box;}
input:focus,select:focus{border-color:#0F7A5A!important;outline:none;box-shadow:0 0 0 3px rgba(15,122,90,.1);}
button:active{opacity:.8;transform:scale(.98);}
@keyframes spin{to{transform:rotate(360deg);}}
select{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24'%3E%3Cpath fill='%23999' d='M7 10l5 5 5-5z'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 12px center;padding-right:32px;}
`;
